stages:
  - init
  - build

services:
  - name: docker:20.10.20-dind
    alias: docker

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_TLS_CERTDIR: "/certs"

get-version:
  tags:
    - kube
  stage: init
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://github.com/ynput/ayon-backend ./backend
    - git clone https://github.com/ynput/ayon-frontend ./frontend
    - echo "VERSION=$(sed -n 's/__version__ = \"\(.*\)\"/\1/p' backend/ayon_server/version.py)" > version_info.txt
    - echo "TODAY=$(date +%Y%m%d)" >> version_info.txt
  artifacts:
    paths:
      - frontend
      - backend
    reports:
      dotenv: version_info.txt

build-server:
  stage: build
  tags:
    - kube
  variables:
    IMAGE_NAME: "ayon-server"
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context .
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/${IMAGE_NAME}:${VERSION}-${TODAY}"
  dependencies:
    - get-version