apiVersion: v1
kind: Service
metadata:
  name: {{ include "ayon.fullname" . }}
  labels:
    {{- include "ayon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ayon.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ayon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
